<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Contrato</title>
</head>
<body>
		<center>CONTRATO DE COMPRA VENTA<br>
			CCV-RP-F EPLGCI 7427-AME-023-09-2014<br>
			COMPRA DE MEZCLA ASFALTICA Y EMULSION CATIONICA
		</center>

		<p><b>CONTRATO DE COMPRA VENTA</b> QUE CELEBRAN POR UNA PARTE EL HONORABLE AYUNTAMIENTO CONSTITUCIONAL DEL MUNICIPIO DE AMECAMECA, ESTADO DE MÉXICO REPRESENTADO POR EL<font color="red"> C.P. CARLOS SANTOS AMADOR</font>, PRESIDENTE MUNICIPAL CONSTITUCIONAL; L.A. MARIBEL PÁEZ AGUILAR, TESORERO MUNICIPAL,<font color="red">PROF. EDGAR MILLA BELLO, SUBDIRECTOR DE ADMINISTRACIÓN</font>; A QUIENES EN LO SUCESIVO Y PARA EFECTOS DEL PRESENTE CONTRATO SE LES DENOMINARA <b>“LA DEPENDENCIA”<b> Y POR LA OTRA PARTE LA PERSONA MORAL<font color="red"> GRUPO CORPORATIVO INTERESTATAL, S.A. DE C.V. REPRESENTADA POR EL LIC. CARLOS ALBERTO RAMOS VEGA, A QUIEN EN LO SUCESIVO Y PARA EFECTOS DEL PRESENTE CONTRATO SE LE DENOMINARA <b>“EL PROVEEDOR”</b>, QUIENES SE OBLIGAN Y SUJETAN AL TENOR DE LAS DECLARACIONES Y CLÁUSULAS SIGUIENTES: ---------------------------------------------------------------------------------------------------------------------</p>

		<p><b>------------------------------- D E C L A R A C I O N E S -----------------------------</p>

		<p><b>PRIMERA: “LA DEPENDENCIA”</b> DECLARA QUE ES UNA PERSONA JURÍDICA COLECTIVA CON  PATRIMONIO PROPIO, DE CONFORMIDAD CON EL ARTICULO 115 FRACCIÓN II PRIMER PÁRRAFO DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS, TENER FACULTADES LEGALES  PARA SUSCRIBIR EL PRESENTE CONTRATO CON FUNDAMENTO EN LOS ARTÍCULOS 112, 113, 122, 123 FRACCIÓN I; 128 FRACCIÓN V Y 138 DE LA CONSTITUCIÓN POLÍTICA DEL ESTADO LIBRE Y SOBERANO DE MÉXICO; LOS ARTÍCULOS 1, 2, 3, 15, 31 FRACCIONES I Y XVIII, 48 FRACCIÓN IV Y 91 FRACCIÓN V DE LA LEY ORGÁNICA MUNICIPAL DEL ESTADO DE MÉXICO; QUE TIENE SU DOMICILIO FISCAL EN PLAZA DE LA CONSTITUCIÓN S/N, COL. CENTRO AMECAMECA, MÉXICO, C. P. 56900. -------------------------------------------------------------------------------------------------------------------------</p>

		<p><b>SEGUNDA: “LA DEPENDENCIA”</b>, MANIFIESTA QUE ESTA FACULTADO PARA SUSCRIBIR EL PRESENTE CONTRATO DE ADJUDICACIÓN DIRECTA Y POSEER LA CAPACIDAD ECONÓMICA NECESARIA Y SUFICIENTE PARA SOLVENTAR LOS COMPROMISOS DERIVADOS DE LAS OBLIGACIONES DEL PRESENTE CONTRATO EN VIRTUD DE QUE SERÁN CON CARGO A<font color="red">LOS RECURSOS PROPIOS, PARA EL EJERCICIO FISCAL DEL AÑO DOS MIL CATORCE.</font> -----------------------------------------------------------</p>

		<p><b>TERCERA:</b> MANIFIESTA <b>“LA DEPENDENCIA”</b>, QUE EL PRESENTE CONTRATO DE ADJUDICACIÓN DIRECTA SE CELEBRA TODA VEZ QUE SE TRATA DE LA COMPRA  <font color="red">DE 58.7 TN DE MEZCLA ASFALTICA, 300 LT EMULSION CATIONICA RR-2K</font> Y QUE EL PROCEDIMIENTO SE REALIZÓ CONFORME A LO ESTABLECIDO EN LOS ARTÍCULOS 48 Y 49 DE LA LEY DE CONTRATACION PUBLICA DEL ESTADO DE MEXICO Y MUNICIPIO POR UN MONTO TOTAL DE <font color="red">$88,769.00 (OCHENTA Y OCHO MIL SETECIENTOS SESENTA Y NUEVE PESOS 00/100 M.N.)</font> IVA INCLUIDO, PACTÁNDOSE LA CONDICIÓN DE PRECIO FIJO.------------------------------------</b>

		<p><b>CUARTA:<b> DECLARA <b>“EL PROVEEDOR ”</b> SER UNA PERSONA MORAL Y ESTAR EN CAPACIDADES DE EJERCICIO Y TENER FACULTADES LEGALES PARA SUSCRIBIR EL PRESENTE CONTRATO Y ACREDITA SU PERSONALIDAD RESPECTO A ESTE CONTRATO,<b> MEDIANTE LA ESCRITURA NO. 248 ACTA CONSTITUTIVA DE SOCIEDAD ANÓNIMA DE CAPITAL VARIABLE, REALIZADA ANTE EL NOTARIO PUBLICO NO. 195 DEL DISTRITO FEDERAL LIC. ANA PATRICIA BANDALA TOLENTINO, TAMBIÉN SE ACREEDITA LA PERSONALIDAD DEL REPRESENTANTE MEDIANTE CREDENCIAL DE ELECTOR FOLIO:</b><font color="red">273783109925</font><b>CON CLAVE DE ELECTOR:</b><font color="red">RMVGCR57021401H900</font> <b>Y CON DOMICILIO PARTICULAR EN</b><font color="red"> CTO PINTORES 19 CD SATELITE 53100 NAUCALPAN, MEX</font>---------------</p>

		<p><b>QUINTA:</b> DECLARA <b>“EL PROVEEDOR”</b>, QUE PARA EFECTOS DEL PRESENTE CONTRATO, SEÑALA COMO DOMICILIO FISCAL, EL UBICADO EN CALLE <font color="red"> BOSQUE DE CIDROS 173 PISO 3 BOSQUES DE LAS LOMAS DISTRITO FEDERAL 05120</font>, PARA EFECTOS DE OÍR  Y RECIBIR NOTIFICACIONES DE CUALQUIER TIPO-----------------------------------------------------------------------------------------------------------</p>

		<p><b>SEXTA:</b> DECLARA <b>“EL PROVEEDOR”</b>, HABER CUMPLIDO SATISFACTORIAMENTE CON LOS REQUISITOS LEGALES Y ADMINISTRATIVOS DE LA ADJUDICACIÓN DIRECTA, QUE CONSISTEN EN: ACTA CONSTITUTIVA, PODER NOTARIAL, CEDULA DE REGISTRO FEDERAL DE CONTRIBUYENTES, CREDENCIAL DE ELECTOR DEL REPRESENTANTE LEGAL.------------------------------------</p>

		<p><b>SÉPTIMA: “EL PROVEEDOR”</b>  MANIFIESTA QUE TIENE LA SOLVENCIA ECONÓMICA NECESARIA Y SUFICIENTE PARA CONTRAER LAS OBLIGACIONES DERIVADAS DEL PRESENTE CONTRATO.-------------------------------------------------------------------------------
		</p>
	
</body>
</html>